name: Security Pipeline
description: 'Perform security tests'

runs:
  using: "composite"

  steps:
    # https://github.com/marketplace/actions/gitleaks
    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@master
    
    # https://github.com/marketplace/actions/anchore-container-scan
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: build local container
      uses: docker/build-push-action@v2
      with:
        tags: localbuild/testimage:latest
        push: false
        load: true

    - name: Scan image
      uses: anchore/scan-action@v3
      with:
        image: "localbuild/testimage:latest"
        fail-build: true
        severity-cutoff: high
        
    - name: Scan current project
      uses: anchore/scan-action@v3
      with:
        path: "."
